//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp16
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int ticketid { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<System.DateTime> dateofjourney { get; set; }
        public Nullable<int> flightid { get; set; }
        public Nullable<int> seatno { get; set; }
    }
}
