//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp16
{
    using System;
    using System.Collections.Generic;
    
    public partial class flight_details
    {
        public int fid { get; set; }
        public string flight_name { get; set; }
        public string sources { get; set; }
        public string destination { get; set; }
        public string arrival_item { get; set; }
        public string departure { get; set; }
        public string flight_class { get; set; }
        public Nullable<decimal> flight_charges { get; set; }
        public Nullable<int> seats { get; set; }
    }
}
