//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp16
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class airportEntities : DbContext
    {
        public airportEntities()
            : base("name=airportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminn> adminns { get; set; }
        public virtual DbSet<Type_Lookup> Type_Lookup { get; set; }
        public virtual DbSet<customer_details> customer_details { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<flight_details> flight_details { get; set; }
    }
}
